# Generated by Django 2.2.12 on 2023-05-31 19:46

from django.db import migrations, models
import django.db.models.deletion
import otree.db.idmap
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iq_test_group', to='otree.Session')),
            ],
            options={
                'db_table': 'IQ_test_group',
            },
            bases=(models.Model, otree.db.idmap.GroupIDMapMixin),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='iq_test_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'IQ_test_subsession',
            },
            bases=(models.Model, otree.db.idmap.SubsessionIDMapMixin),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_role', otree.db.models.StringField(max_length=10000, null=True)),
                ('correct_answer', otree.db.models.IntegerField(null=True)),
                ('combined_score', otree.db.models.IntegerField(default=0, null=True)),
                ('answer_entered1', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], null=True, verbose_name='Q1 Please select your answer')),
                ('answer_entered2', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], null=True, verbose_name='Q2 Please select your answer')),
                ('answer_entered3', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], null=True, verbose_name='Q3 Please select your answer')),
                ('answer_entered4', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], null=True, verbose_name='Q4 Please select your answer')),
                ('answer_entered5', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], null=True, verbose_name='Q5 Please select your answer')),
                ('answer_entered6', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], null=True, verbose_name='Q6 Please select your answer')),
                ('answer_entered7', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], null=True, verbose_name='Q7 Please select your answer')),
                ('answer_entered8', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], null=True, verbose_name='Q8 Please select your answer')),
                ('answer_entered9', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], null=True, verbose_name='Q9 Please select your answer')),
                ('answer_entered10', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], null=True, verbose_name='Q10 Please select your answer')),
                ('score1', otree.db.models.IntegerField(default=0, null=True)),
                ('score2', otree.db.models.IntegerField(default=0, null=True)),
                ('score3', otree.db.models.IntegerField(default=0, null=True)),
                ('score4', otree.db.models.IntegerField(default=0, null=True)),
                ('score5', otree.db.models.IntegerField(default=0, null=True)),
                ('score6', otree.db.models.IntegerField(default=0, null=True)),
                ('score7', otree.db.models.IntegerField(default=0, null=True)),
                ('score8', otree.db.models.IntegerField(default=0, null=True)),
                ('score9', otree.db.models.IntegerField(default=0, null=True)),
                ('score10', otree.db.models.IntegerField(default=0, null=True)),
                ('result', otree.db.models.IntegerField(default=0, null=True)),
                ('noisy_feedback1', otree.db.models.IntegerField(default=0, null=True)),
                ('noisy_feedback2', otree.db.models.IntegerField(default=0, null=True)),
                ('noisy_feedback3', otree.db.models.IntegerField(default=0, null=True)),
                ('gender', otree.db.models.StringField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Prefer not ot say', 'Prefer not ot say')], max_length=10000, null=True, verbose_name='Please state your gender')),
                ('age', otree.db.models.StringField(choices=[('18-24', '18-24'), ('25-30', '25-30'), ('30-49', '30-49'), ('larger than 49', 'larger than 49'), ('Prefer not ot say', 'Prefer not ot say')], max_length=10000, null=True, verbose_name='Please select your age bracket')),
                ('education', otree.db.models.StringField(choices=[('High school or lower', 'High school or lower'), ('Bachelor degree', 'Bachelor degree'), ('Master degree', 'Master degree'), ('PhD degree', 'PhD degree'), ('Other', 'Other'), ('Prefer not ot say', 'Prefer not ot say')], max_length=10000, null=True, verbose_name='Please state your highest obtained level of education')),
                ('employment', otree.db.models.StringField(choices=[('Employed', 'Employed'), ('Unemployed', 'Unemployed'), ('Student', 'Student'), ('Prefer not ot say', 'Prefer not ot say')], max_length=10000, null=True, verbose_name='Please state your current state of employment')),
                ('marriage', otree.db.models.StringField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Other', 'Other'), ('Prefer not ot say', 'Prefer not ot say')], max_length=10000, null=True, verbose_name='Please state your current marital status')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='IQ_test.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iq_test_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iq_test_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IQ_test.Subsession')),
            ],
            options={
                'db_table': 'IQ_test_player',
            },
            bases=(models.Model, otree.db.idmap.PlayerIDMapMixin),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IQ_test.Subsession'),
        ),
    ]
