# Generated by Django 2.2.12 on 2023-05-31 20:22

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('IQ_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='result1',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='result2',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='result3',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
    ]
