# Generated by Django 2.2.12 on 2023-05-31 20:33

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('IQ_test', '0002_auto_20230531_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='result1',
        ),
        migrations.RemoveField(
            model_name='player',
            name='result2',
        ),
        migrations.RemoveField(
            model_name='player',
            name='result3',
        ),
        migrations.AddField(
            model_name='player',
            name='NFresult1',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='NFresult2',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='NFresult3',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
    ]
