# Generated by Django 2.2.12 on 2023-06-02 15:37

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('IQ_test', '0003_auto_20230531_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='current_player',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
    ]
